"""End-to-end tests for the README quick-start journey.

Each test drives the real CLI entry point (argparse included) inside a
temp directory and asserts the exact on-disk layout the README promises:
init -> new -> load -> env -> validate -> unload.
"""
import os
import shutil

import yaml

from gcontext import __version__

CONTEXT_FILES = [
    "llms.txt",
    "system.md",
    "structure.md",
    "principles.md",
    "module_features.md",
    "secrets.md",
]

GENERATED_HEADER_PREFIX = "<!-- GENERATED by gcontext."

INTEGRATION_INFO_SECTIONS = [
    "## Purpose",
    "## Where it lives",
    "## Auth & access",
    "## Key entities",
    "## Operations",
    "## Examples",
]


def _give_secret(workspace, name, secret):
    """Declare a secret in an existing module's manifest."""
    manifest_path = workspace / "modules-repo" / name / "module.yaml"
    data = yaml.safe_load(manifest_path.read_text())
    data["secrets"] = [secret]
    manifest_path.write_text(yaml.dump(data))


# ---------------------------------------------------------------------------
# gcontext init
# ---------------------------------------------------------------------------

class TestInit:
    def test_creates_workspace_layout(self, workspace, run):
        code, out = run("init")
        assert code == 0
        assert "Created modules-repo/" in out

        # Seeded starter module, present but NOT loaded
        seed = workspace / "modules-repo" / "seed"
        for fname in ["module.yaml", "llms.txt", "info.md"]:
            assert (seed / fname).is_file()
        assert not (workspace / "context" / "seed").exists()

        # Generated context files
        for fname in CONTEXT_FILES:
            assert (workspace / "context" / fname).is_file()
        assert "No modules loaded." in (workspace / "context" / "system.md").read_text()

        # Bootstrap files
        agents = (workspace / "AGENTS.md").read_text()
        assert "<!-- gcontext:start -->" in agents
        assert "context/system.md" in agents
        assert (workspace / "CLAUDE.md").read_text() == "@AGENTS.md\n"
        assert ".env" in (workspace / ".gitignore").read_text().splitlines()

    def test_context_files_carry_generated_header(self, workspace, run):
        run("init")
        for fname in CONTEXT_FILES:
            content = (workspace / "context" / fname).read_text()
            assert content.startswith(GENERATED_HEADER_PREFIX), fname
            assert content.count(GENERATED_HEADER_PREFIX) == 1, fname

    def test_init_twice_errors_and_overwrites_nothing(self, workspace, run):
        run("init")
        sentinel = workspace / "modules-repo" / "seed" / "my-notes.md"
        sentinel.write_text("precious user content\n")

        code, out = run("init")
        assert code == 1
        assert "already initialized" in out
        assert sentinel.read_text() == "precious user content\n"

    def test_init_recreates_missing_context(self, workspace, run):
        run("init")
        shutil.rmtree(workspace / "context")

        code, out = run("init")
        assert code == 0
        assert "Recreated context/" in out
        for fname in CONTEXT_FILES:
            assert (workspace / "context" / fname).is_file()

    def test_init_refuses_foreign_context_dir(self, workspace, run):
        (workspace / "context").mkdir()
        code, out = run("init")
        assert code == 1
        assert "does not look like a gcontext workspace" in out
        assert not (workspace / "modules-repo").exists()

    def test_init_preserves_existing_user_files(self, workspace, run):
        (workspace / "AGENTS.md").write_text("# My agents\n\nMy own rules.\n")
        (workspace / "CLAUDE.md").write_text("my claude setup\n")
        (workspace / ".gitignore").write_text("node_modules\n")

        run("init")

        agents = (workspace / "AGENTS.md").read_text()
        assert "My own rules." in agents
        assert "<!-- gcontext:start -->" in agents
        assert (workspace / "CLAUDE.md").read_text() == "my claude setup\n"
        gitignore = (workspace / ".gitignore").read_text().splitlines()
        assert "node_modules" in gitignore
        assert ".env" in gitignore


# ---------------------------------------------------------------------------
# gcontext new
# ---------------------------------------------------------------------------

class TestNew:
    def test_new_integration(self, workspace, run):
        run("init")
        code, out = run("new", "integration", "postgres")
        assert code == 0

        mod = workspace / "modules-repo" / "postgres"
        manifest = yaml.safe_load((mod / "module.yaml").read_text())
        assert manifest["name"] == "postgres"
        assert "kind" not in manifest  # integration is the default, omitted

        info = (mod / "info.md").read_text()
        for section in INTEGRATION_INFO_SECTIONS:
            assert section in info

        llms = (mod / "llms.txt").read_text()
        assert "[info.md](info.md)" in llms
        assert "[module.yaml](module.yaml)" in llms
        assert "## Where to write" in llms

        # Created, not loaded
        assert not (workspace / "context" / "postgres").exists()

    def test_new_task(self, workspace, run):
        run("init")
        code, _ = run("new", "task", "migrate-db")
        assert code == 0

        mod = workspace / "modules-repo" / "migrate-db"
        assert yaml.safe_load((mod / "module.yaml").read_text())["kind"] == "task"
        assert "## Goal" in (mod / "brief.md").read_text()
        assert "## Subtasks" in (mod / "status.md").read_text()

    def test_new_workflow(self, workspace, run):
        run("init")
        code, _ = run("new", "workflow", "release")
        assert code == 0

        mod = workspace / "modules-repo" / "release"
        assert yaml.safe_load((mod / "module.yaml").read_text())["kind"] == "workflow"
        assert "## Steps" in (mod / "steps.md").read_text()

    def test_new_with_summary(self, workspace, run):
        run("init")
        run("new", "integration", "stripe", "Stripe payments API")
        llms = (workspace / "modules-repo" / "stripe" / "llms.txt").read_text()
        assert "> Stripe payments API" in llms

    def test_new_rejects_invalid_name(self, workspace, run):
        run("init")
        code, out = run("new", "integration", "bad name!")
        assert code == 1
        assert "Invalid module name" in out
        assert not (workspace / "modules-repo" / "bad name!").exists()

    def test_new_rejects_duplicate(self, workspace, run):
        run("init")
        run("new", "integration", "postgres")
        code, out = run("new", "integration", "postgres")
        assert code == 1
        assert "already exists" in out

    def test_new_requires_workspace(self, workspace, run):
        code, out = run("new", "integration", "postgres")
        assert code == 1
        assert "workspace not initialized" in out


# ---------------------------------------------------------------------------
# gcontext load
# ---------------------------------------------------------------------------

class TestLoad:
    def test_load_creates_relative_symlink_and_regenerates_index(self, workspace, run):
        run("init")
        run("new", "integration", "stripe", "Stripe payments API")
        code, out = run("load", "stripe")
        assert code == 0
        assert "Loaded stripe" in out

        link = workspace / "context" / "stripe"
        assert link.is_symlink()
        assert os.readlink(link) == os.path.join("..", "modules-repo", "stripe")

        root_llms = (workspace / "context" / "llms.txt").read_text()
        assert "- [stripe](stripe/llms.txt): Stripe payments API" in root_llms

        system = (workspace / "context" / "system.md").read_text()
        assert "| stripe | integration | Stripe payments API |" in system

    def test_load_warns_on_placeholder_summary(self, workspace, run):
        run("init")
        run("new", "integration", "postgres")  # no summary given
        _, out = run("load", "postgres")
        assert "placeholder summary" in out

    def test_load_multiple(self, workspace, run):
        run("init")
        run("new", "integration", "postgres")
        code, _ = run("load", "seed", "postgres")
        assert code == 0
        assert (workspace / "context" / "seed").is_symlink()
        assert (workspace / "context" / "postgres").is_symlink()

        root_llms = (workspace / "context" / "llms.txt").read_text()
        assert "[seed](seed/llms.txt)" in root_llms
        assert "[postgres](postgres/llms.txt)" in root_llms

    def test_load_unknown_module_errors(self, workspace, run):
        run("init")
        code, out = run("load", "nope")
        assert code == 1
        assert "not found in modules-repo/" in out

    def test_load_twice_is_noop(self, workspace, run):
        run("init")
        run("load", "seed")
        code, out = run("load", "seed")
        assert code == 0
        assert "Already loaded: seed" in out

    def test_load_generates_env_example_from_secrets(self, workspace, run):
        run("init")
        run("new", "integration", "vault")
        _give_secret(workspace, "vault", "GCTX_TEST_TOKEN")

        run("load", "vault")
        env_example = (workspace / ".env.example").read_text()
        assert "# vault" in env_example
        assert "GCTX_TEST_TOKEN=" in env_example

        run("unload", "vault")
        assert not (workspace / ".env.example").exists()


# ---------------------------------------------------------------------------
# gcontext env
# ---------------------------------------------------------------------------

class TestEnv:
    def test_env_with_no_secrets(self, workspace, run):
        run("init")
        run("load", "seed")
        code, out = run("env")
        assert code == 0
        assert "No loaded modules declare secrets." in out

    def test_env_fails_on_missing_then_passes_with_dotenv(self, workspace, run, monkeypatch):
        monkeypatch.delenv("GCTX_TEST_TOKEN", raising=False)
        run("init")
        run("new", "integration", "vault")
        _give_secret(workspace, "vault", "GCTX_TEST_TOKEN")
        run("load", "vault")

        code, out = run("env")
        assert code == 1
        assert "missing" in out

        (workspace / ".env").write_text("GCTX_TEST_TOKEN=hunter2\n")
        code, out = run("env")
        assert code == 0
        assert "All variables set." in out


# ---------------------------------------------------------------------------
# gcontext validate
# ---------------------------------------------------------------------------

class TestValidate:
    def test_validate_fresh_workspace_passes(self, workspace, run):
        run("init")
        run("new", "integration", "postgres")
        run("new", "task", "migrate-db")
        run("new", "workflow", "release")
        code, out = run("validate")
        assert code == 0
        for name in ["seed", "postgres", "migrate-db", "release"]:
            assert f"{name}  PASS" in out

    def test_validate_fails_on_missing_required_file(self, workspace, run):
        run("init")
        run("new", "integration", "postgres")
        (workspace / "modules-repo" / "postgres" / "info.md").unlink()
        code, out = run("validate", "postgres")
        assert code == 1
        assert "missing info.md" in out

    def test_validate_fails_on_broken_llms_link(self, workspace, run):
        run("init")
        run("new", "integration", "postgres")
        llms = workspace / "modules-repo" / "postgres" / "llms.txt"
        llms.write_text(llms.read_text() + "- [gone.md](gone.md): vanished\n")
        code, out = run("validate", "postgres")
        assert code == 1
        assert "links to 'gone.md' which does not exist" in out

    def test_validate_fails_on_name_mismatch(self, workspace, run):
        run("init")
        run("new", "integration", "postgres")
        manifest = workspace / "modules-repo" / "postgres" / "module.yaml"
        manifest.write_text("name: postgresql\n")
        code, out = run("validate", "postgres")
        assert code == 1
        assert "does not match directory name" in out

    def test_validate_reports_dangling_symlink(self, workspace, run):
        run("init")
        run("new", "integration", "postgres")
        run("load", "postgres")
        shutil.rmtree(workspace / "modules-repo" / "postgres")
        code, out = run("validate")
        assert code == 1
        assert "dangling symlink" in out

    def test_validate_unknown_module_errors(self, workspace, run):
        run("init")
        code, out = run("validate", "nope")
        assert code == 1
        assert "module directory not found" in out


# ---------------------------------------------------------------------------
# gcontext unload / ls / --version
# ---------------------------------------------------------------------------

class TestUnload:
    def test_unload_removes_link_and_regenerates(self, workspace, run):
        run("init")
        run("load", "seed")
        code, out = run("unload", "seed")
        assert code == 0
        assert "Unloaded seed" in out
        assert not (workspace / "context" / "seed").exists()
        assert "[seed]" not in (workspace / "context" / "llms.txt").read_text()
        # Module itself is untouched
        assert (workspace / "modules-repo" / "seed" / "info.md").is_file()

    def test_unload_not_loaded_errors(self, workspace, run):
        run("init")
        code, out = run("unload", "seed")
        assert code == 1
        assert "is not loaded" in out


class TestLs:
    def test_ls_splits_loaded_and_available(self, workspace, run):
        run("init")
        run("new", "integration", "postgres")
        run("load", "postgres")
        code, out = run("ls")
        assert code == 0
        loaded_section = out[out.index("LOADED"):out.index("AVAILABLE")]
        assert "postgres" in loaded_section
        assert "seed" in out[out.index("AVAILABLE"):]


class TestVersion:
    def test_version(self, run):
        code, out = run("--version")
        assert code == 0
        assert f"gcontext {__version__}" in out


# ---------------------------------------------------------------------------
# The full README quick start, as one script
# ---------------------------------------------------------------------------

class TestQuickStartJourney:
    def test_readme_quick_start(self, workspace, run, monkeypatch):
        monkeypatch.delenv("GCTX_TEST_TOKEN", raising=False)

        # 1. init an empty directory
        code, _ = run("init")
        assert code == 0

        # 2. scaffold an integration
        code, _ = run("new", "integration", "vault", "Secrets vault API")
        assert code == 0
        _give_secret(workspace, "vault", "GCTX_TEST_TOKEN")

        # 3. load it
        code, _ = run("load", "vault")
        assert code == 0
        assert (workspace / "context" / "vault").is_symlink()
        assert "Secrets vault API" in (workspace / "context" / "llms.txt").read_text()
        assert "GCTX_TEST_TOKEN=" in (workspace / ".env.example").read_text()

        # 4. env fails until .env is filled in
        code, _ = run("env")
        assert code == 1
        (workspace / ".env").write_text("GCTX_TEST_TOKEN=s3cret\n")
        code, _ = run("env")
        assert code == 0

        # 5. everything validates
        code, _ = run("validate")
        assert code == 0

        # 6. unload cleans up
        code, _ = run("unload", "vault")
        assert code == 0
        assert not (workspace / "context" / "vault").exists()
        assert not (workspace / ".env.example").exists()
