#!/usr/bin/env python3
"""gcontext — gcontext module manager.

Usage:
    gcontext init
    gcontext new <kind> <name> [summary]
    gcontext load <name> [name2 ...]
    gcontext unload <name>
    gcontext ls
    gcontext env
    gcontext validate [name]
"""
import argparse
import importlib.resources
import os
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths — all relative to CWD (the user's project directory)
# ---------------------------------------------------------------------------
MODULES_DIR = Path.cwd() / "modules-repo"
CONTEXT_DIR = Path.cwd() / "context"

# ---------------------------------------------------------------------------
# Package-data helpers
# ---------------------------------------------------------------------------

def _read_pkg_text(package: str, *path_parts: str) -> str:
    """Read a text file bundled inside a Python package."""
    return importlib.resources.files(package).joinpath(*path_parts).read_text()


def _copy_pkg_file(package: str, path_parts: tuple[str, ...], dest: Path) -> None:
    """Copy a text file from package data to a filesystem path."""
    src = importlib.resources.files(package).joinpath(*path_parts)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(src.read_text())


# ---------------------------------------------------------------------------
# Imports from the core package (installed alongside gcontext)
# ---------------------------------------------------------------------------
from core.manifest import ModuleManifest, read_manifest, write_manifest
from core.kind_specs import KIND_SPECS, INTEGRATION_INFO_SECTIONS
from core.schemas import validate_module_name
from core.llms_gen import generate_root_llms_txt, generate_structure_md, generate_system_md


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_GENERATED_HEADER_PREFIX = "<!-- GENERATED by gcontext."
_GENERATED_HEADER = (
    "<!-- GENERATED by gcontext. This file is rewritten on every "
    "`gcontext load`/`unload`. Do not edit it directly — edit modules in "
    "modules-repo/ instead. -->\n"
)
_PLACEHOLDER_SUMMARY = "One-line summary of this module"


def _require_workspace():
    """Exit with an error unless the CWD contains an initialized workspace."""
    if not MODULES_DIR.is_dir():
        print("Error: workspace not initialized. Run: gcontext init")
        sys.exit(1)
    if not CONTEXT_DIR.is_dir():
        print("Error: context/ is missing. Run: gcontext init to recreate it.")
        sys.exit(1)


def _prepend_header(path: Path) -> None:
    """Prepend the generated-file header to a context/ file (idempotent)."""
    content = path.read_text()
    if not content.startswith(_GENERATED_HEADER_PREFIX):
        path.write_text(_GENERATED_HEADER + "\n" + content)


def _prune_stale_links():
    """Remove context/ symlinks whose modules-repo/ target no longer exists."""
    for p in sorted(CONTEXT_DIR.iterdir()):
        if p.is_symlink() and not p.exists():
            p.unlink()
            print(
                f"Warning: module '{p.name}' is missing from modules-repo/ — "
                "removed stale link from context/."
            )


def _warn_placeholder_summaries(names):
    """Warn about just-loaded modules whose llms.txt summary is the placeholder."""
    from core.llms_gen import extract_module_summary

    for name in names:
        llms_file = MODULES_DIR / name / "llms.txt"
        if llms_file.exists() and extract_module_summary(llms_file.read_text()) == _PLACEHOLDER_SUMMARY:
            print(
                f"Warning: '{name}' still has a placeholder summary in llms.txt — "
                "agents route by these descriptions; fill it in."
            )


def _copy_static_files():
    """Copy static template files into context/."""
    for name in ["principles.md", "module_features.md"]:
        _copy_pkg_file("core", ("templates", name), CONTEXT_DIR / name)
        _prepend_header(CONTEXT_DIR / name)
    _copy_pkg_file("gcontext", ("data", "secrets.md"), CONTEXT_DIR / "secrets.md")
    _prepend_header(CONTEXT_DIR / "secrets.md")


def _regenerate():
    """Regenerate all auto-generated files in context/."""
    _prune_stale_links()
    # OSS-specific system.md template (no cloud-only features like cron jobs
    # or browser apps; mentions the seeded example module).
    template_content = _read_pkg_text("gcontext", "data", "system.md")
    generate_root_llms_txt(CONTEXT_DIR)
    generate_structure_md(CONTEXT_DIR, audience="oss")
    generate_system_md(CONTEXT_DIR, template_content)
    for name in ["llms.txt", "structure.md", "system.md"]:
        _prepend_header(CONTEXT_DIR / name)
    _copy_static_files()
    _generate_env_example()
    _generate_agents_md()
    _generate_claude_md()


def _regen_and_report():
    """Regenerate context/ and print the loaded-module count."""
    _regenerate()
    n = sum(1 for p in CONTEXT_DIR.iterdir() if p.is_symlink())
    print(f"Regenerated context/ ({n} module{'' if n == 1 else 's'})")


# Managed bootstrap block written to AGENTS.md at the project root. AGENTS.md is
# the tool-agnostic convention most coding agents auto-load; it points the agent
# at the generated context/system.md entry file (the CLI cannot inject a system
# prompt the way the hosted platform does, so this pointer is the bootstrap).
_AGENTS_START = "<!-- gcontext:start -->"
_AGENTS_END = "<!-- gcontext:end -->"
_AGENTS_BLOCK = f"""{_AGENTS_START}
## gcontext workspace

This is a gcontext workspace. Before doing anything else, read `context/system.md` — \
it explains how to operate the loaded context modules: navigate the `llms.txt` tree, \
run module scripts, and handle secrets. Re-read it whenever modules are loaded or unloaded.
{_AGENTS_END}"""


def _generate_agents_md():
    """Write/refresh the gcontext bootstrap block in AGENTS.md at the project root.

    Non-destructive: only the content between the gcontext markers is managed;
    any other content the user adds to AGENTS.md is preserved.
    """
    agents = Path.cwd() / "AGENTS.md"
    if not agents.exists():
        agents.write_text(f"# AGENTS.md\n\n{_AGENTS_BLOCK}\n")
        return

    content = agents.read_text()
    pattern = re.compile(
        re.escape(_AGENTS_START) + r".*?" + re.escape(_AGENTS_END), re.DOTALL
    )
    if pattern.search(content):
        new_content = pattern.sub(lambda _: _AGENTS_BLOCK, content)
    else:
        new_content = content.rstrip("\n") + "\n\n" + _AGENTS_BLOCK + "\n"

    if new_content != content:
        agents.write_text(new_content)


def _generate_claude_md():
    """Create CLAUDE.md importing AGENTS.md, if the user doesn't have one.

    Claude Code auto-loads CLAUDE.md (not AGENTS.md); the @import keeps
    AGENTS.md as the single source of truth for every agent. Never touches
    an existing CLAUDE.md.
    """
    claude = Path.cwd() / "CLAUDE.md"
    if not claude.exists():
        claude.write_text("@AGENTS.md\n")


def _generate_env_example():
    """Generate .env.example from all loaded modules' secrets lists."""
    lines = []
    for mod_dir in sorted(CONTEXT_DIR.iterdir()):
        if not mod_dir.is_dir() or mod_dir.name.startswith("."):
            continue
        manifest = read_manifest(mod_dir)
        if manifest.secrets:
            lines.append(f"# {manifest.name}")
            for secret in manifest.secrets:
                lines.append(f"{secret}=")
            lines.append("")
    env_example = Path.cwd() / ".env.example"
    if lines:
        env_example.write_text("\n".join(lines) + "\n")
    elif env_example.exists():
        env_example.unlink()


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

_EXAMPLE_FILES = ["module.yaml", "llms.txt", "info.md"]


def cmd_init(args):
    """Initialize the workspace."""
    has_modules = MODULES_DIR.is_dir()
    has_context = CONTEXT_DIR.is_dir()
    if has_modules and has_context:
        print(
            "Error: workspace already initialized. "
            "Context files in context/ are regenerated by load/unload."
        )
        sys.exit(1)
    if has_context and not has_modules:
        print(
            "Error: a context/ directory exists here but modules-repo/ does not — "
            "this does not look like a gcontext workspace. Move or rename context/ first."
        )
        sys.exit(1)
    repairing = has_modules and not has_context

    for parent in Path.cwd().parents:
        if (parent / "modules-repo").is_dir() and (parent / "context").is_dir():
            print(f"Note: you are inside an existing workspace at {parent}")
            break

    MODULES_DIR.mkdir(exist_ok=True)
    CONTEXT_DIR.mkdir(exist_ok=True)

    # Seed the example module when modules-repo is empty
    if not any(MODULES_DIR.iterdir()):
        example_dest = MODULES_DIR / "example"
        example_dest.mkdir(parents=True, exist_ok=True)
        for fname in _EXAMPLE_FILES:
            _copy_pkg_file("gcontext", ("data", "example", fname), example_dest / fname)

    # Create .gitignore if it doesn't exist
    gitignore = Path.cwd() / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(".env\n")
    else:
        content = gitignore.read_text()
        if ".env" not in content.splitlines():
            gitignore.write_text(content.rstrip("\n") + "\n.env\n")

    _regenerate()
    if repairing:
        print("Recreated context/ (modules-repo/ already existed)")
    else:
        print("Created modules-repo/")
        print("Created context/")
        print(
            "Ready. Open your agent and ask it to create a module — "
            "or run: gcontext new integration <name>"
        )


def cmd_new(args):
    """Scaffold a new module."""
    _require_workspace()
    kind = args.kind
    name = args.name

    try:
        name = validate_module_name(name)
    except ValueError as e:
        print(f"Error: {e}")
        sys.exit(1)

    mod_dir = MODULES_DIR / name
    if mod_dir.exists():
        print(f"Error: module '{name}' already exists at {mod_dir}")
        sys.exit(1)

    mod_dir.mkdir(parents=True)
    spec = KIND_SPECS[kind]

    # Write module.yaml
    manifest = ModuleManifest(name=name, kind=kind)
    write_manifest(mod_dir, manifest)

    # Write llms.txt — link every required file for the kind
    summary = args.summary or _PLACEHOLDER_SUMMARY
    file_descs = {
        "status.md": "Current status and subtask progress",
    }
    llms_content = f"# {name}\n\n> {summary}\n\n"
    for f in spec.required_files:
        if f in ("module.yaml", "llms.txt"):
            continue
        desc = spec.starter_outline if f == spec.starter_file else file_descs.get(f, "Module file")
        llms_content += f"- [{f}]({f}): {desc}\n"
    llms_content += "- [module.yaml](module.yaml): Module configuration\n"
    if spec.default_growth_folders:
        llms_content += "\n## Where to write\n"
        for ga in spec.default_growth_folders:
            llms_content += f"- {ga['name']} -> `{ga['path']}`\n"
    (mod_dir / "llms.txt").write_text(llms_content)

    # Write starter file(s)
    if kind == "integration":
        sections = []
        for s in INTEGRATION_INFO_SECTIONS:
            sections.append(f"## {s.name}\n{s.purpose}\n")
        (mod_dir / "info.md").write_text(f"# {name}\n\n" + "\n".join(sections))

    elif kind == "task":
        (mod_dir / "brief.md").write_text(
            f"# {name}\n\n## Goal\nWhat this task should accomplish.\n\n## Context\nBackground and constraints.\n"
        )
        (mod_dir / "status.md").write_text(
            "# Status\n\n## Subtasks\n- [ ] First subtask\n"
        )

    elif kind == "workflow":
        (mod_dir / "steps.md").write_text(
            f"# {name}\n\n## Steps\n1. First step\n2. Second step\n"
        )

    for f in spec.required_files:
        print(f"Created modules-repo/{name}/{f}")
    print(f'Module "{name}" created. Edit the files, then load it with: gcontext load {name}')


def _interactive_load():
    """Interactive module selector for loading."""
    from simple_term_menu import TerminalMenu

    if not MODULES_DIR.exists():
        print("No modules-repo/ directory. Run: gcontext init")
        sys.exit(1)

    loaded_names = {p.name for p in CONTEXT_DIR.iterdir() if p.is_symlink()} if CONTEXT_DIR.exists() else set()
    all_modules = sorted(p.name for p in MODULES_DIR.iterdir() if p.is_dir())

    if not all_modules:
        print("No modules found. Create one with: gcontext new integration <name>")
        return []

    from core.llms_gen import extract_module_summary

    entries = []
    preselected = []
    for i, name in enumerate(all_modules):
        manifest = read_manifest(MODULES_DIR / name)
        llms_file = MODULES_DIR / name / "llms.txt"
        summary = extract_module_summary(llms_file.read_text()) if llms_file.exists() else ""
        label = f"{name:<20s} ({manifest.kind})"
        if summary:
            label += f"  {summary}"
        entries.append(label)
        if name in loaded_names:
            preselected.append(i)

    menu = TerminalMenu(
        entries,
        multi_select=True,
        show_multi_select_hint=True,
        preselected_entries=preselected,
        multi_select_select_on_accept=False,
        title="Select modules to load (space to toggle, enter to confirm):",
    )
    result = menu.show()

    if result is None:
        print("Cancelled.")
        return []

    selected_indices = menu.chosen_menu_indices or ()
    selected_names = [all_modules[i] for i in selected_indices]

    # Load newly selected, unload newly deselected
    to_load = [n for n in selected_names if n not in loaded_names]
    to_unload = [n for n in loaded_names if n not in selected_names]

    for name in to_load:
        link_path = CONTEXT_DIR / name
        link_path.symlink_to(Path("..") / "modules-repo" / name)
        print(f"Loaded {name}")

    for name in to_unload:
        link_path = CONTEXT_DIR / name
        if link_path.is_symlink():
            link_path.unlink()
            print(f"Unloaded {name}")

    _warn_placeholder_summaries(to_load)
    return to_load + to_unload


def cmd_load(args):
    """Load modules into the workspace via symlinks."""
    _require_workspace()

    if not args.names:
        changes = _interactive_load()
        if changes:
            _regen_and_report()
        return

    just_loaded = []
    for name in args.names:
        mod_source = MODULES_DIR / name
        if not mod_source.is_dir():
            print(f"Error: module '{name}' not found in modules-repo/")
            sys.exit(1)

        link_path = CONTEXT_DIR / name
        if link_path.is_symlink() or link_path.exists():
            print(f"Already loaded: {name}")
            continue

        # Relative symlink for portability
        link_path.symlink_to(Path("..") / "modules-repo" / name)
        print(f"Loaded {name}")
        just_loaded.append(name)

    _regen_and_report()
    _warn_placeholder_summaries(just_loaded)


def _interactive_unload():
    """Interactive module selector for unloading."""
    from simple_term_menu import TerminalMenu

    loaded = sorted(p.name for p in CONTEXT_DIR.iterdir() if p.is_symlink())
    if not loaded:
        print("No modules loaded.")
        return []

    from core.llms_gen import extract_module_summary

    entries = []
    for name in loaded:
        manifest = read_manifest(MODULES_DIR / name)
        llms_file = MODULES_DIR / name / "llms.txt"
        summary = extract_module_summary(llms_file.read_text()) if llms_file.exists() else ""
        label = f"{name:<20s} ({manifest.kind})"
        if summary:
            label += f"  {summary}"
        entries.append(label)

    menu = TerminalMenu(
        entries,
        multi_select=True,
        show_multi_select_hint=True,
        multi_select_select_on_accept=False,
        title="Select modules to unload (space to toggle, enter to confirm):",
    )
    result = menu.show()

    if result is None:
        print("Cancelled.")
        return []

    selected_indices = menu.chosen_menu_indices or ()
    to_unload = [loaded[i] for i in selected_indices]

    for name in to_unload:
        (CONTEXT_DIR / name).unlink()
        print(f"Unloaded {name}")

    return to_unload


def cmd_unload(args):
    """Remove a module from the workspace."""
    _require_workspace()

    if not args.name:
        changes = _interactive_unload()
        if changes:
            _regen_and_report()
        return

    name = args.name
    link_path = CONTEXT_DIR / name

    if not link_path.is_symlink():
        print(f"Error: '{name}' is not loaded")
        sys.exit(1)

    link_path.unlink()
    print(f"Unloaded {name}")

    _regen_and_report()


def cmd_ls(args):
    """List all modules and their status."""
    _require_workspace()

    loaded_names = {p.name for p in CONTEXT_DIR.iterdir() if p.is_symlink()}
    missing_loaded = sorted(n for n in loaded_names if not (CONTEXT_DIR / n).exists())

    all_modules = sorted(p.name for p in MODULES_DIR.iterdir() if p.is_dir())

    if not all_modules and not missing_loaded:
        print("No modules found. Create one with: gcontext new integration <name>")
        return

    loaded = [(n, read_manifest(MODULES_DIR / n)) for n in all_modules if n in loaded_names]
    available = [(n, read_manifest(MODULES_DIR / n)) for n in all_modules if n not in loaded_names]

    from core.llms_gen import extract_module_summary

    def _summary(name):
        llms_file = MODULES_DIR / name / "llms.txt"
        if llms_file.exists():
            return extract_module_summary(llms_file.read_text())
        return ""

    if loaded or missing_loaded:
        print("LOADED")
        for name, m in loaded:
            summary = _summary(name)
            print(f"  {name:<20s} {m.kind:<14s} {summary}")
        for name in missing_loaded:
            print(f"  {name:<20s} MISSING")
        for name in missing_loaded:
            print(
                f"Warning: module '{name}' is missing from modules-repo/ — "
                "its link in context/ is stale."
            )
        print()

    if available:
        print("AVAILABLE")
        for name, m in available:
            summary = _summary(name)
            print(f"  {name:<20s} {m.kind:<14s} {summary}")


def cmd_env(args):
    """Check which secret variables are set or missing."""
    _require_workspace()

    # Try to load .env file into a dict (don't inject into os.environ)
    env_vars = dict(os.environ)
    env_file = Path.cwd() / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                env_vars[key.strip()] = value.strip()

    any_missing = False
    any_secrets = False

    for mod_dir in sorted(CONTEXT_DIR.iterdir()):
        if not mod_dir.is_dir() or mod_dir.name.startswith("."):
            continue
        manifest = read_manifest(mod_dir)
        if not manifest.secrets:
            continue
        any_secrets = True
        print(f"\n{manifest.name}")
        for secret in manifest.secrets:
            if secret in env_vars and env_vars[secret]:
                print(f"  {secret:<30s} set")
            else:
                print(f"  {secret:<30s} missing")
                any_missing = True

    if not any_secrets:
        print("No loaded modules declare secrets.")
        return

    if any_missing:
        print("\nMissing variables. Add them to .env")
        sys.exit(1)
    else:
        print("\nAll variables set.")


def cmd_validate(args):
    """Validate module structure."""
    _require_workspace()

    if args.name:
        names = [args.name]
    else:
        names = sorted(p.name for p in MODULES_DIR.iterdir() if p.is_dir())

    # Loaded symlinks whose modules-repo/ target is gone
    dangling = sorted(
        p.name for p in CONTEXT_DIR.iterdir() if p.is_symlink() and not p.exists()
    )
    if not args.name:
        # In all-modules mode, dangling links are extra failures; in
        # single-module mode the not-found check below already covers it.
        dangling_to_report = dangling
    else:
        dangling_to_report = []

    if not names and not dangling_to_report:
        print("No modules to validate.")
        return

    all_pass = True
    for name in dangling_to_report:
        print(f"{name}  FAIL")
        print("  - loaded in context/ but missing from modules-repo/ (dangling symlink)")
        all_pass = False
    for name in names:
        mod_dir = MODULES_DIR / name
        if not mod_dir.is_dir():
            print(f"{name}  FAIL  module directory not found")
            all_pass = False
            continue

        errors = []
        manifest = None

        # Check module.yaml
        manifest_path = mod_dir / "module.yaml"
        if not manifest_path.exists():
            errors.append("missing module.yaml")
        else:
            try:
                manifest = read_manifest(mod_dir)
            except Exception as e:
                errors.append(f"invalid module.yaml: {e}")

            if manifest and manifest.kind not in KIND_SPECS:
                errors.append(f"unknown kind '{manifest.kind}'")

            if manifest and manifest.name != name:
                errors.append(
                    f"module.yaml name '{manifest.name}' does not match directory name '{name}'"
                )

        # Check required files per kind
        if manifest_path.exists() and manifest:
            spec = KIND_SPECS.get(manifest.kind)
            if spec:
                for req_file in spec.required_files:
                    if not (mod_dir / req_file).exists():
                        errors.append(f"missing {req_file} (required for {manifest.kind} kind)")

        # Check llms.txt links
        llms_path = mod_dir / "llms.txt"
        if llms_path.exists():
            for line in llms_path.read_text().splitlines():
                # Parse markdown links: [text](path)
                for match in re.finditer(r'\[.*?\]\((.+?)\)', line):
                    link_target = match.group(1)
                    if link_target.startswith("http"):
                        continue
                    if not (mod_dir / link_target).exists():
                        errors.append(f"llms.txt links to '{link_target}' which does not exist")

        if errors:
            print(f"{name}  FAIL")
            for e in errors:
                print(f"  - {e}")
            all_pass = False
        else:
            print(f"{name}  PASS")

    if not all_pass:
        sys.exit(1)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    from gcontext import __version__

    parser = argparse.ArgumentParser(
        prog="gcontext",
        description="gcontext — module manager",
    )
    parser.add_argument("--version", action="version", version=f"gcontext {__version__}")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # init
    subparsers.add_parser("init", help="Initialize the workspace")

    # new
    new_parser = subparsers.add_parser("new", help="Scaffold a new module")
    new_parser.add_argument("kind", choices=list(KIND_SPECS.keys()), help="Module kind")
    new_parser.add_argument("name", help="Module name")
    new_parser.add_argument(
        "summary", nargs="?", help="One-line module summary for llms.txt (optional)"
    )

    # load
    load_parser = subparsers.add_parser("load", help="Load modules into workspace")
    load_parser.add_argument("names", nargs="*", help="Module names to load (interactive if omitted)")

    # unload
    unload_parser = subparsers.add_parser("unload", help="Unload a module from workspace")
    unload_parser.add_argument("name", nargs="?", help="Module name to unload (interactive if omitted)")

    # ls
    subparsers.add_parser("ls", help="List all modules")

    # env
    subparsers.add_parser("env", help="Check secret variable status")

    # validate
    validate_parser = subparsers.add_parser("validate", help="Validate module structure")
    validate_parser.add_argument("name", nargs="?", help="Module name (validates all if omitted)")

    args = parser.parse_args()
    if args.command == "init":
        cmd_init(args)
    elif args.command == "new":
        cmd_new(args)
    elif args.command == "load":
        cmd_load(args)
    elif args.command == "unload":
        cmd_unload(args)
    elif args.command == "ls":
        cmd_ls(args)
    elif args.command == "env":
        cmd_env(args)
    elif args.command == "validate":
        cmd_validate(args)
    elif args.command is None:
        parser.print_help()
        sys.exit(1)
    else:
        print(f"Command '{args.command}' not yet implemented")
        sys.exit(1)


if __name__ == "__main__":
    main()
